### Recuperar todas las peliculas
GET http://localhost:3000/movies

### Recuperar una pelicula por ID
GET http://localhost:3000/movies/a89c386e-cb06-11f0-99e3-a2aa5b933c49

### Recuperar peliculas por genero
GET http://localhost:3000/movies?genre=Action

### Crear una pelicula
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1972,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg",
  "genre": [
    "Crime",
    "Drama"
  ],
  "rate": 9.2
}

### Eliminar una pelicula
DELETE http://localhost:3000/movies/4553e907-cb07-11f0-99e3-a2aa5b933c49

### Actualizar una pelicula
PATCH http://localhost:3000/movies/a89c386e-cb06-11f0-99e3-a2aa5b933c49
Content-Type: application/json

{
  "year": 2010,
  "rate": 9.0
}